var annotated_dup =
[
    [ "boost", null, [
      [ "pfr", null, [
        [ "detail", null, [
          [ "can_not_apply", "structboost_1_1pfr_1_1detail_1_1can__not__apply.html", null ],
          [ "equal_impl", "structboost_1_1pfr_1_1detail_1_1equal__impl.html", null ],
          [ "equal_impl< N, N >", "structboost_1_1pfr_1_1detail_1_1equal__impl_3_01N_00_01N_01_4.html", null ],
          [ "fn_def_lref", "structboost_1_1pfr_1_1detail_1_1fn__def__lref.html", null ],
          [ "fn_def_lref< T, U, N, true >", "structboost_1_1pfr_1_1detail_1_1fn__def__lref_3_01T_00_01U_00_01N_00_01true_01_4.html", null ],
          [ "fn_def_rref", "structboost_1_1pfr_1_1detail_1_1fn__def__rref.html", null ],
          [ "fn_def_rref< T, U, N, true >", "structboost_1_1pfr_1_1detail_1_1fn__def__rref_3_01T_00_01U_00_01N_00_01true_01_4.html", null ],
          [ "greater_equal_impl", "structboost_1_1pfr_1_1detail_1_1greater__equal__impl.html", null ],
          [ "greater_equal_impl< N, N >", "structboost_1_1pfr_1_1detail_1_1greater__equal__impl_3_01N_00_01N_01_4.html", null ],
          [ "greater_impl", "structboost_1_1pfr_1_1detail_1_1greater__impl.html", null ],
          [ "greater_impl< N, N >", "structboost_1_1pfr_1_1detail_1_1greater__impl_3_01N_00_01N_01_4.html", null ],
          [ "hash_impl", "structboost_1_1pfr_1_1detail_1_1hash__impl.html", null ],
          [ "hash_impl< N, N >", "structboost_1_1pfr_1_1detail_1_1hash__impl_3_01N_00_01N_01_4.html", null ],
          [ "internal_aligned_storage", "structboost_1_1pfr_1_1detail_1_1internal__aligned__storage.html", null ],
          [ "io_fields_impl", "structboost_1_1pfr_1_1detail_1_1io__fields__impl.html", null ],
          [ "io_impl", "structboost_1_1pfr_1_1detail_1_1io__impl.html", null ],
          [ "less_equal_impl", "structboost_1_1pfr_1_1detail_1_1less__equal__impl.html", null ],
          [ "less_equal_impl< N, N >", "structboost_1_1pfr_1_1detail_1_1less__equal__impl_3_01N_00_01N_01_4.html", null ],
          [ "less_impl", "structboost_1_1pfr_1_1detail_1_1less__impl.html", null ],
          [ "less_impl< N, N >", "structboost_1_1pfr_1_1detail_1_1less__impl_3_01N_00_01N_01_4.html", null ],
          [ "loophole_type_list_lref", "structboost_1_1pfr_1_1detail_1_1loophole__type__list__lref.html", null ],
          [ "loophole_type_list_lref< T, std::index_sequence< I... > >", "structboost_1_1pfr_1_1detail_1_1loophole__type__list__lref_3_01T_00_01std_1_1index__sequence_3_01I_8_8_8_01_4_01_4.html", null ],
          [ "loophole_type_list_rref", "structboost_1_1pfr_1_1detail_1_1loophole__type__list__rref.html", null ],
          [ "loophole_type_list_rref< T, std::index_sequence< I... > >", "structboost_1_1pfr_1_1detail_1_1loophole__type__list__rref_3_01T_00_01std_1_1index__sequence_3_01I_8_8_8_01_4_01_4.html", null ],
          [ "loophole_type_list_selector", "structboost_1_1pfr_1_1detail_1_1loophole__type__list__selector.html", null ],
          [ "loophole_type_list_selector< false, T, U >", "structboost_1_1pfr_1_1detail_1_1loophole__type__list__selector_3_01false_00_01T_00_01U_01_4.html", null ],
          [ "loophole_ubiq_lref", "structboost_1_1pfr_1_1detail_1_1loophole__ubiq__lref.html", null ],
          [ "loophole_ubiq_rref", "structboost_1_1pfr_1_1detail_1_1loophole__ubiq__rref.html", null ],
          [ "not_appliable", "structboost_1_1pfr_1_1detail_1_1not__appliable.html", null ],
          [ "not_equal_impl", "structboost_1_1pfr_1_1detail_1_1not__equal__impl.html", null ],
          [ "not_equal_impl< N, N >", "structboost_1_1pfr_1_1detail_1_1not__equal__impl_3_01N_00_01N_01_4.html", null ],
          [ "offset_based_getter", "classboost_1_1pfr_1_1detail_1_1offset__based__getter.html", null ],
          [ "print_impl", "structboost_1_1pfr_1_1detail_1_1print__impl.html", null ],
          [ "print_impl< I, I >", "structboost_1_1pfr_1_1detail_1_1print__impl_3_01I_00_01I_01_4.html", null ],
          [ "read_impl", "structboost_1_1pfr_1_1detail_1_1read__impl.html", null ],
          [ "read_impl< I, I >", "structboost_1_1pfr_1_1detail_1_1read__impl_3_01I_00_01I_01_4.html", null ],
          [ "sequence_tuple_getter", "structboost_1_1pfr_1_1detail_1_1sequence__tuple__getter.html", null ],
          [ "tag", "structboost_1_1pfr_1_1detail_1_1tag.html", null ],
          [ "tie_from_structure_tuple", "structboost_1_1pfr_1_1detail_1_1tie__from__structure__tuple.html", null ],
          [ "tuple_of_aligned_storage", "structboost_1_1pfr_1_1detail_1_1tuple__of__aligned__storage.html", null ],
          [ "tuple_of_aligned_storage< sequence_tuple::tuple< Ts... > >", "structboost_1_1pfr_1_1detail_1_1tuple__of__aligned__storage_3_01sequence__tuple_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ]
        ] ],
        [ "equal_to", "structboost_1_1pfr_1_1equal__to.html", "structboost_1_1pfr_1_1equal__to" ],
        [ "greater", "structboost_1_1pfr_1_1greater.html", "structboost_1_1pfr_1_1greater" ],
        [ "greater_equal", "structboost_1_1pfr_1_1greater__equal.html", "structboost_1_1pfr_1_1greater__equal" ],
        [ "hash", "structboost_1_1pfr_1_1hash.html", "structboost_1_1pfr_1_1hash" ],
        [ "is_reflectable", "structboost_1_1pfr_1_1is__reflectable.html", null ],
        [ "is_reflectable< const T, WhatFor >", "structboost_1_1pfr_1_1is__reflectable_3_01const_01T_00_01WhatFor_01_4.html", null ],
        [ "is_reflectable< const volatile T, WhatFor >", "structboost_1_1pfr_1_1is__reflectable_3_01const_01volatile_01T_00_01WhatFor_01_4.html", null ],
        [ "is_reflectable< volatile T, WhatFor >", "structboost_1_1pfr_1_1is__reflectable_3_01volatile_01T_00_01WhatFor_01_4.html", null ],
        [ "less", "structboost_1_1pfr_1_1less.html", "structboost_1_1pfr_1_1less" ],
        [ "less_equal", "structboost_1_1pfr_1_1less__equal.html", "structboost_1_1pfr_1_1less__equal" ],
        [ "not_equal", "structboost_1_1pfr_1_1not__equal.html", "structboost_1_1pfr_1_1not__equal" ]
      ] ]
    ] ],
    [ "cppgres", null, [
      [ "utils", null, [
        [ "function_traits", null, [
          [ "function_traits", "structcppgres_1_1utils_1_1function__traits_1_1function__traits.html", null ],
          [ "function_traits< R(&)(Args...)>", "structcppgres_1_1utils_1_1function__traits_1_1function__traits_3_01R_07_6_08_07Args_8_8_8_08_4.html", null ],
          [ "function_traits< R(*)(Args...)>", "structcppgres_1_1utils_1_1function__traits_1_1function__traits_3_01R_07_5_08_07Args_8_8_8_08_4.html", null ],
          [ "function_traits< R(Args...)>", "structcppgres_1_1utils_1_1function__traits_1_1function__traits_3_01R_07Args_8_8_8_08_4.html", null ],
          [ "function_traits< R(C::*)(Args...) const >", "structcppgres_1_1utils_1_1function__traits_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", null ],
          [ "invoke_result_from_tuple", "structcppgres_1_1utils_1_1function__traits_1_1invoke__result__from__tuple.html", null ],
          [ "invoke_result_from_tuple< Func, std::tuple< Args... > >", "structcppgres_1_1utils_1_1function__traits_1_1invoke__result__from__tuple_3_01Func_00_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4.html", null ]
        ] ],
        [ "is_std_tuple", "structcppgres_1_1utils_1_1is__std__tuple.html", null ],
        [ "is_std_tuple< std::tuple< Ts... > >", "structcppgres_1_1utils_1_1is__std__tuple_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
        [ "remove_optional", "structcppgres_1_1utils_1_1remove__optional.html", null ],
        [ "remove_optional< std::optional< T > >", "structcppgres_1_1utils_1_1remove__optional_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
        [ "tuple_traits_impl", "structcppgres_1_1utils_1_1tuple__traits__impl.html", "structcppgres_1_1utils_1_1tuple__traits__impl" ],
        [ "tuple_traits_impl< T, std::void_t< decltype(std::tuple_size< T >::value)> >", "structcppgres_1_1utils_1_1tuple__traits__impl_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1tuc17d0c8e371e8a53d2c38db131d82a30.html", null ]
      ] ],
      [ "abstract_memory_context", "structcppgres_1_1abstract__memory__context.html", null ],
      [ "all_from_nullable_datum", "structcppgres_1_1all__from__nullable__datum.html", null ],
      [ "alloc_set_memory_context", "structcppgres_1_1alloc__set__memory__context.html", null ],
      [ "always_current_memory_context", "structcppgres_1_1always__current__memory__context.html", null ],
      [ "bytea", "structcppgres_1_1bytea.html", null ],
      [ "current_postgres_function", "structcppgres_1_1current__postgres__function.html", null ],
      [ "datum", "structcppgres_1_1datum.html", null ],
      [ "datum_conversion", "structcppgres_1_1datum__conversion.html", null ],
      [ "datum_conversion< bool >", "structcppgres_1_1datum__conversion_3_01bool_01_4.html", null ],
      [ "datum_conversion< bytea >", "structcppgres_1_1datum__conversion_3_01bytea_01_4.html", null ],
      [ "datum_conversion< const char * >", "structcppgres_1_1datum__conversion_3_01const_01char_01_5_01_4.html", null ],
      [ "datum_conversion< int16_t >", "structcppgres_1_1datum__conversion_3_01int16__t_01_4.html", null ],
      [ "datum_conversion< int32_t >", "structcppgres_1_1datum__conversion_3_01int32__t_01_4.html", null ],
      [ "datum_conversion< int64_t >", "structcppgres_1_1datum__conversion_3_01int64__t_01_4.html", null ],
      [ "datum_conversion< oid >", "structcppgres_1_1datum__conversion_3_01oid_01_4.html", null ],
      [ "datum_conversion< size_t >", "structcppgres_1_1datum__conversion_3_01size__t_01_4.html", null ],
      [ "datum_conversion< std::string >", "structcppgres_1_1datum__conversion_3_01std_1_1string_01_4.html", null ],
      [ "datum_conversion< std::string_view >", "structcppgres_1_1datum__conversion_3_01std_1_1string__view_01_4.html", null ],
      [ "datum_conversion< T, std::enable_if_t< expanded_varlena_type< T > > >", "structcppgres_1_1datum__conversion_3_01T_00_01std_1_1enable__if__t_3_01expanded__varlena__type_3_01T_01_4_01_4_01_4.html", null ],
      [ "datum_conversion< text >", "structcppgres_1_1datum__conversion_3_01text_01_4.html", null ],
      [ "executor", "structcppgres_1_1executor.html", null ],
      [ "expanded_varlena", "structcppgres_1_1expanded__varlena.html", null ],
      [ "ffi_guard", "structcppgres_1_1ffi__guard.html", null ],
      [ "internal_subtransaction", "structcppgres_1_1internal__subtransaction.html", null ],
      [ "memory_context", "structcppgres_1_1memory__context.html", null ],
      [ "memory_context_allocator", "structcppgres_1_1memory__context__allocator.html", null ],
      [ "memory_context_scope", "structcppgres_1_1memory__context__scope.html", null ],
      [ "named_type", "structcppgres_1_1named__type.html", "structcppgres_1_1named__type" ],
      [ "node_tag_traits", "structcppgres_1_1node__tag__traits.html", null ],
      [ "node_traits", "structcppgres_1_1node__traits.html", null ],
      [ "non_by_value_type", "structcppgres_1_1non__by__value__type.html", null ],
      [ "null_datum_exception", "classcppgres_1_1null__datum__exception.html", null ],
      [ "nullable_datum", "structcppgres_1_1nullable__datum.html", null ],
      [ "owned_memory_context", "structcppgres_1_1owned__memory__context.html", null ],
      [ "pg_exception", "classcppgres_1_1pg__exception.html", null ],
      [ "pointer_gone_exception", "structcppgres_1_1pointer__gone__exception.html", null ],
      [ "postgres_function", "structcppgres_1_1postgres__function.html", "structcppgres_1_1postgres__function" ],
      [ "set_iterator_traits", "structcppgres_1_1set__iterator__traits.html", null ],
      [ "spi_executor", "structcppgres_1_1spi__executor.html", "structcppgres_1_1spi__executor" ],
      [ "spi_nonatomic_executor", "structcppgres_1_1spi__nonatomic__executor.html", "structcppgres_1_1spi__nonatomic__executor" ],
      [ "spi_plan", "structcppgres_1_1spi__plan.html", null ],
      [ "syscache", "structcppgres_1_1syscache.html", null ],
      [ "syscache_traits", "structcppgres_1_1syscache__traits.html", null ],
      [ "syscache_traits< Form_pg_type >", "structcppgres_1_1syscache__traits_3_01Form__pg__type_01_4.html", null ],
      [ "text", "structcppgres_1_1text.html", null ],
      [ "tracking_memory_context", "structcppgres_1_1tracking__memory__context.html", null ],
      [ "type", "structcppgres_1_1type.html", "structcppgres_1_1type" ],
      [ "type_traits", "structcppgres_1_1type__traits.html", null ],
      [ "type_traits< bool >", "structcppgres_1_1type__traits_3_01bool_01_4.html", null ],
      [ "type_traits< byte_array >", "structcppgres_1_1type__traits_3_01byte__array_01_4.html", null ],
      [ "type_traits< bytea >", "structcppgres_1_1type__traits_3_01bytea_01_4.html", null ],
      [ "type_traits< expanded_varlena< F > >", "structcppgres_1_1type__traits_3_01expanded__varlena_3_01F_01_4_01_4.html", null ],
      [ "type_traits< I >", "structcppgres_1_1type__traits_3_01I_01_4.html", null ],
      [ "type_traits< int16_t >", "structcppgres_1_1type__traits_3_01int16__t_01_4.html", null ],
      [ "type_traits< int32_t >", "structcppgres_1_1type__traits_3_01int32__t_01_4.html", null ],
      [ "type_traits< int64_t >", "structcppgres_1_1type__traits_3_01int64__t_01_4.html", null ],
      [ "type_traits< int8_t >", "structcppgres_1_1type__traits_3_01int8__t_01_4.html", null ],
      [ "type_traits< std::string >", "structcppgres_1_1type__traits_3_01std_1_1string_01_4.html", null ],
      [ "type_traits< std::string_view >", "structcppgres_1_1type__traits_3_01std_1_1string__view_01_4.html", null ],
      [ "type_traits< T >", "structcppgres_1_1type__traits_3_01T_01_4.html", null ],
      [ "type_traits< text >", "structcppgres_1_1type__traits_3_01text_01_4.html", null ],
      [ "unsupported_type", "structcppgres_1_1unsupported__type.html", null ],
      [ "varlena", "structcppgres_1_1varlena.html", null ]
    ] ]
];