var annotated_dup =
[
    [ "cppgres", null, [
      [ "nodes", null, [
        [ "unknown_node", "structcppgres_1_1nodes_1_1unknown__node.html", null ]
      ] ],
      [ "utils", null, [
        [ "function_traits", null, [
          [ "function_traits", "structcppgres_1_1utils_1_1function__traits_1_1function__traits.html", null ],
          [ "function_traits< R(&)(Args...)>", "structcppgres_1_1utils_1_1function__traits_1_1function__traits_3_01R_07_6_08_07Args_8_8_8_08_4.html", null ],
          [ "function_traits< R(*)(Args...)>", "structcppgres_1_1utils_1_1function__traits_1_1function__traits_3_01R_07_5_08_07Args_8_8_8_08_4.html", null ],
          [ "function_traits< R(Args...)>", "structcppgres_1_1utils_1_1function__traits_1_1function__traits_3_01R_07Args_8_8_8_08_4.html", null ],
          [ "function_traits< R(C::*)(Args...) const >", "structcppgres_1_1utils_1_1function__traits_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", null ],
          [ "invoke_result_from_tuple", "structcppgres_1_1utils_1_1function__traits_1_1invoke__result__from__tuple.html", null ],
          [ "invoke_result_from_tuple< Func, std::tuple< Args... > >", "structcppgres_1_1utils_1_1function__traits_1_1invoke__result__from__tuple_3_01Func_00_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4.html", null ]
        ] ],
        [ "is_std_tuple", "structcppgres_1_1utils_1_1is__std__tuple.html", null ],
        [ "is_std_tuple< std::tuple< Ts... > >", "structcppgres_1_1utils_1_1is__std__tuple_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
        [ "maybe_ref", "structcppgres_1_1utils_1_1maybe__ref.html", null ],
        [ "owned_cstring", "structcppgres_1_1utils_1_1owned__cstring.html", null ],
        [ "remove_optional", "structcppgres_1_1utils_1_1remove__optional.html", null ],
        [ "remove_optional< std::optional< T > >", "structcppgres_1_1utils_1_1remove__optional_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
        [ "tuple_traits_impl", "structcppgres_1_1utils_1_1tuple__traits__impl.html", "structcppgres_1_1utils_1_1tuple__traits__impl" ],
        [ "tuple_traits_impl< T, std::enable_if_t< std::is_aggregate_v< T > > >", "structcppgres_1_1utils_1_1tuple__traits__impl_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__aggregate__v_3_01T_01_4_01_4_01_4.html", null ],
        [ "tuple_traits_impl< T, std::void_t< decltype(std::tuple_size< T >::value)> >", "structcppgres_1_1utils_1_1tuple__traits__impl_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1tuc17d0c8e371e8a53d2c38db131d82a30.html", null ]
      ] ],
      [ "abstract_memory_context", "structcppgres_1_1abstract__memory__context.html", "structcppgres_1_1abstract__memory__context" ],
      [ "all_from_nullable_datum", "structcppgres_1_1all__from__nullable__datum.html", null ],
      [ "alloc_set_memory_context", "structcppgres_1_1alloc__set__memory__context.html", null ],
      [ "always_current_memory_context", "structcppgres_1_1always__current__memory__context.html", null ],
      [ "backend", "structcppgres_1_1backend.html", null ],
      [ "background_worker", "structcppgres_1_1background__worker.html", "structcppgres_1_1background__worker" ],
      [ "background_worker_bypass_allow_connection", "structcppgres_1_1background__worker__bypass__allow__connection.html", null ],
      [ "background_worker_database_conection_flag", "structcppgres_1_1background__worker__database__conection__flag.html", null ],
      [ "bytea", "structcppgres_1_1bytea.html", null ],
      [ "collation", "structcppgres_1_1collation.html", null ],
      [ "current_background_worker", "structcppgres_1_1current__background__worker.html", "structcppgres_1_1current__background__worker" ],
      [ "current_postgres_function", "structcppgres_1_1current__postgres__function.html", null ],
      [ "datum", "structcppgres_1_1datum.html", null ],
      [ "datum_conversion", "structcppgres_1_1datum__conversion.html", null ],
      [ "datum_conversion< bool >", "structcppgres_1_1datum__conversion_3_01bool_01_4.html", null ],
      [ "datum_conversion< byte_array >", "structcppgres_1_1datum__conversion_3_01byte__array_01_4.html", null ],
      [ "datum_conversion< bytea >", "structcppgres_1_1datum__conversion_3_01bytea_01_4.html", null ],
      [ "datum_conversion< char[N]>", "structcppgres_1_1datum__conversion_3_01char_0fN_0e_4.html", null ],
      [ "datum_conversion< const char * >", "structcppgres_1_1datum__conversion_3_01const_01char_01_5_01_4.html", null ],
      [ "datum_conversion< datum >", "structcppgres_1_1datum__conversion_3_01datum_01_4.html", null ],
      [ "datum_conversion< double >", "structcppgres_1_1datum__conversion_3_01double_01_4.html", null ],
      [ "datum_conversion< float >", "structcppgres_1_1datum__conversion_3_01float_01_4.html", null ],
      [ "datum_conversion< function< Args... > >", "structcppgres_1_1datum__conversion_3_01function_3_01Args_8_8_8_01_4_01_4.html", null ],
      [ "datum_conversion< int16_t >", "structcppgres_1_1datum__conversion_3_01int16__t_01_4.html", null ],
      [ "datum_conversion< int32_t >", "structcppgres_1_1datum__conversion_3_01int32__t_01_4.html", null ],
      [ "datum_conversion< int64_t >", "structcppgres_1_1datum__conversion_3_01int64__t_01_4.html", null ],
      [ "datum_conversion< nullable_datum >", "structcppgres_1_1datum__conversion_3_01nullable__datum_01_4.html", null ],
      [ "datum_conversion< oid >", "structcppgres_1_1datum__conversion_3_01oid_01_4.html", null ],
      [ "datum_conversion< record >", "structcppgres_1_1datum__conversion_3_01record_01_4.html", null ],
      [ "datum_conversion< role >", "structcppgres_1_1datum__conversion_3_01role_01_4.html", null ],
      [ "datum_conversion< size_t >", "structcppgres_1_1datum__conversion_3_01size__t_01_4.html", null ],
      [ "datum_conversion< std::string >", "structcppgres_1_1datum__conversion_3_01std_1_1string_01_4.html", null ],
      [ "datum_conversion< std::string_view >", "structcppgres_1_1datum__conversion_3_01std_1_1string__view_01_4.html", null ],
      [ "datum_conversion< T >", "structcppgres_1_1datum__conversion_3_01T_01_4.html", null ],
      [ "datum_conversion< T, std::enable_if_t< expanded_varlena_type< T > > >", "structcppgres_1_1datum__conversion_3_01T_00_01std_1_1enable__if__t_3_01expanded__varlena__type_3_01T_01_4_01_4_01_4.html", null ],
      [ "datum_conversion< T, std::enable_if_t< utils::is_optional< T > > >", "structcppgres_1_1datum__conversion_3_01T_00_01std_1_1enable__if__t_3_01utils_1_1is__optional_3_01T_01_4_01_4_01_4.html", null ],
      [ "datum_conversion< text >", "structcppgres_1_1datum__conversion_3_01text_01_4.html", null ],
      [ "datum_conversion< value >", "structcppgres_1_1datum__conversion_3_01value_01_4.html", null ],
      [ "datum_conversion< void * >", "structcppgres_1_1datum__conversion_3_01void_01_5_01_4.html", null ],
      [ "default_datum_conversion", "structcppgres_1_1default__datum__conversion.html", null ],
      [ "exception_guard", "structcppgres_1_1exception__guard.html", null ],
      [ "executor", "structcppgres_1_1executor.html", null ],
      [ "expanded_varlena", "structcppgres_1_1expanded__varlena.html", null ],
      [ "expr_node_walker", "structcppgres_1_1expr__node__walker.html", null ],
      [ "expr_node_walker< nodes::Query >", "structcppgres_1_1expr__node__walker_3_01nodes_1_1Query_01_4.html", null ],
      [ "ffi_guard", "structcppgres_1_1ffi__guard.html", null ],
      [ "function", "structcppgres_1_1function.html", null ],
      [ "function_call_info", "structcppgres_1_1function__call__info.html", "structcppgres_1_1function__call__info" ],
      [ "heap_tuple", "structcppgres_1_1heap__tuple.html", null ],
      [ "internal_subtransaction", "structcppgres_1_1internal__subtransaction.html", null ],
      [ "memory_context", "structcppgres_1_1memory__context.html", null ],
      [ "memory_context_allocator", "structcppgres_1_1memory__context__allocator.html", null ],
      [ "memory_context_scope", "structcppgres_1_1memory__context__scope.html", null ],
      [ "name", "structcppgres_1_1name.html", null ],
      [ "named_type", "structcppgres_1_1named__type.html", "structcppgres_1_1named__type" ],
      [ "node_coverage", "structcppgres_1_1node__coverage.html", null ],
      [ "node_tag_traits", "structcppgres_1_1node__tag__traits.html", null ],
      [ "node_traits", "structcppgres_1_1node__traits.html", null ],
      [ "node_walker", "structcppgres_1_1node__walker.html", "structcppgres_1_1node__walker" ],
      [ "node_walker< nodes::List >", "structcppgres_1_1node__walker_3_01nodes_1_1List_01_4.html", null ],
      [ "node_walker< nodes::RawStmt >", "structcppgres_1_1node__walker_3_01nodes_1_1RawStmt_01_4.html", null ],
      [ "non_by_value_type", "structcppgres_1_1non__by__value__type.html", null ],
      [ "null_datum_exception", "classcppgres_1_1null__datum__exception.html", null ],
      [ "nullable_datum", "structcppgres_1_1nullable__datum.html", null ],
      [ "oid", "structcppgres_1_1oid.html", null ],
      [ "owned_memory_context", "structcppgres_1_1owned__memory__context.html", null ],
      [ "pg_exception", "classcppgres_1_1pg__exception.html", null ],
      [ "pointer_gone_exception", "structcppgres_1_1pointer__gone__exception.html", null ],
      [ "postgres_function", "structcppgres_1_1postgres__function.html", "structcppgres_1_1postgres__function" ],
      [ "raw_expr_node_walker", "structcppgres_1_1raw__expr__node__walker.html", null ],
      [ "record", "structcppgres_1_1record.html", "structcppgres_1_1record" ],
      [ "role", "structcppgres_1_1role.html", null ],
      [ "security_context", "structcppgres_1_1security__context.html", null ],
      [ "set_iterator_traits", "structcppgres_1_1set__iterator__traits.html", null ],
      [ "spi_executor", "structcppgres_1_1spi__executor.html", "structcppgres_1_1spi__executor" ],
      [ "spi_nonatomic_executor", "structcppgres_1_1spi__nonatomic__executor.html", "structcppgres_1_1spi__nonatomic__executor" ],
      [ "spi_plan", "structcppgres_1_1spi__plan.html", null ],
      [ "syscache", "structcppgres_1_1syscache.html", "structcppgres_1_1syscache" ],
      [ "syscache_traits", "structcppgres_1_1syscache__traits.html", null ],
      [ "syscache_traits< Form_pg_proc >", "structcppgres_1_1syscache__traits_3_01Form__pg__proc_01_4.html", null ],
      [ "syscache_traits< Form_pg_type >", "structcppgres_1_1syscache__traits_3_01Form__pg__type_01_4.html", null ],
      [ "text", "structcppgres_1_1text.html", null ],
      [ "tracking_memory_context", "structcppgres_1_1tracking__memory__context.html", null ],
      [ "transaction", "structcppgres_1_1transaction.html", null ],
      [ "transaction_id", "structcppgres_1_1transaction__id.html", null ],
      [ "tuple_descriptor", "structcppgres_1_1tuple__descriptor.html", "structcppgres_1_1tuple__descriptor" ],
      [ "type", "structcppgres_1_1type.html", "structcppgres_1_1type" ],
      [ "type_traits", "structcppgres_1_1type__traits.html", null ],
      [ "type_traits< bool >", "structcppgres_1_1type__traits_3_01bool_01_4.html", null ],
      [ "type_traits< byte_array >", "structcppgres_1_1type__traits_3_01byte__array_01_4.html", null ],
      [ "type_traits< bytea >", "structcppgres_1_1type__traits_3_01bytea_01_4.html", null ],
      [ "type_traits< char * >", "structcppgres_1_1type__traits_3_01char_01_5_01_4.html", null ],
      [ "type_traits< const char * >", "structcppgres_1_1type__traits_3_01const_01char_01_5_01_4.html", null ],
      [ "type_traits< const char[N]>", "structcppgres_1_1type__traits_3_01const_01char_0fN_0e_4.html", null ],
      [ "type_traits< datum >", "structcppgres_1_1type__traits_3_01datum_01_4.html", null ],
      [ "type_traits< double >", "structcppgres_1_1type__traits_3_01double_01_4.html", null ],
      [ "type_traits< expanded_varlena< F > >", "structcppgres_1_1type__traits_3_01expanded__varlena_3_01F_01_4_01_4.html", null ],
      [ "type_traits< float >", "structcppgres_1_1type__traits_3_01float_01_4.html", null ],
      [ "type_traits< function< Args... > >", "structcppgres_1_1type__traits_3_01function_3_01Args_8_8_8_01_4_01_4.html", null ],
      [ "type_traits< I >", "structcppgres_1_1type__traits_3_01I_01_4.html", null ],
      [ "type_traits< int16_t >", "structcppgres_1_1type__traits_3_01int16__t_01_4.html", null ],
      [ "type_traits< int32_t >", "structcppgres_1_1type__traits_3_01int32__t_01_4.html", null ],
      [ "type_traits< int64_t >", "structcppgres_1_1type__traits_3_01int64__t_01_4.html", null ],
      [ "type_traits< int8_t >", "structcppgres_1_1type__traits_3_01int8__t_01_4.html", null ],
      [ "type_traits< nullable_datum >", "structcppgres_1_1type__traits_3_01nullable__datum_01_4.html", null ],
      [ "type_traits< oid >", "structcppgres_1_1type__traits_3_01oid_01_4.html", null ],
      [ "type_traits< record >", "structcppgres_1_1type__traits_3_01record_01_4.html", null ],
      [ "type_traits< role >", "structcppgres_1_1type__traits_3_01role_01_4.html", null ],
      [ "type_traits< S, std::enable_if_t< utils::is_std_tuple< S >::value > >", "structcppgres_1_1type__traits_3_01S_00_01std_1_1enable__if__t_3_01utils_1_1is__std__tuple_3_01S_01_4_1_1value_01_4_01_4.html", null ],
      [ "type_traits< std::optional< T > >", "structcppgres_1_1type__traits_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
      [ "type_traits< std::string >", "structcppgres_1_1type__traits_3_01std_1_1string_01_4.html", null ],
      [ "type_traits< std::string_view >", "structcppgres_1_1type__traits_3_01std_1_1string__view_01_4.html", null ],
      [ "type_traits< T >", "structcppgres_1_1type__traits_3_01T_01_4.html", null ],
      [ "type_traits< text >", "structcppgres_1_1type__traits_3_01text_01_4.html", null ],
      [ "type_traits< value >", "structcppgres_1_1type__traits_3_01value_01_4.html", null ],
      [ "type_traits< void * >", "structcppgres_1_1type__traits_3_01void_01_5_01_4.html", null ],
      [ "type_traits< void >", "structcppgres_1_1type__traits_3_01void_01_4.html", null ],
      [ "unsupported_type", "structcppgres_1_1unsupported__type.html", null ],
      [ "value", "structcppgres_1_1value.html", null ],
      [ "varlena", "structcppgres_1_1varlena.html", null ],
      [ "worker", "structcppgres_1_1worker.html", "structcppgres_1_1worker" ]
    ] ]
];