var dir_af1bb9dae411b5b1b5161db3c243cdc2 =
[
    [ "utils", "dir_dca1f27a09f228d6b5929aa1d69d04c4.html", "dir_dca1f27a09f228d6b5929aa1d69d04c4" ],
    [ "backend.hpp", "backend_8hpp_source.html", null ],
    [ "bgw.hpp", "bgw_8hpp.html", "bgw_8hpp" ],
    [ "datum.hpp", "datum_8hpp.html", "datum_8hpp" ],
    [ "error.hpp", "error_8hpp.html", "error_8hpp" ],
    [ "exception.hpp", "exception_8hpp.html", "exception_8hpp" ],
    [ "exception_impl.hpp", "exception__impl_8hpp.html", null ],
    [ "executor.hpp", "executor_8hpp.html", "executor_8hpp" ],
    [ "function.hpp", "function_8hpp.html", "function_8hpp" ],
    [ "guard.hpp", "guard_8hpp.html", "guard_8hpp" ],
    [ "heap_tuple.hpp", "heap__tuple_8hpp_source.html", null ],
    [ "imports.h", "imports_8h.html", null ],
    [ "memory.hpp", "memory_8hpp.html", "memory_8hpp" ],
    [ "name.hpp", "name_8hpp_source.html", null ],
    [ "node.hpp", "node_8hpp_source.html", null ],
    [ "record.hpp", "record_8hpp_source.html", null ],
    [ "set.hpp", "set_8hpp.html", "set_8hpp" ],
    [ "syscache.hpp", "syscache_8hpp_source.html", null ],
    [ "threading.hpp", "threading_8hpp_source.html", null ],
    [ "type.hpp", "type_8hpp.html", "type_8hpp" ],
    [ "types.hpp", "types_8hpp.html", "types_8hpp" ],
    [ "value.hpp", "value_8hpp_source.html", null ],
    [ "xact.hpp", "xact_8hpp.html", "xact_8hpp" ]
];