var searchData=
[
  ['a_5fmemory_5fcontext_0',['a_memory_context',['../conceptcppgres_1_1a__memory__context.html',1,'cppgres']]],
  ['a_5fvector_1',['a_vector',['../conceptcppgres_1_1a__vector.html',1,'cppgres']]],
  ['c_5fstr_5favailable_2',['c_str_available',['../conceptcppgres_1_1utils_1_1c__str__available.html',1,'cppgres::utils']]],
  ['connect_3',['connect',['../structcppgres_1_1current__background__worker.html#af2dd9091ee501563274f792b878c81b4',1,'cppgres::current_background_worker::connect(std::string dbname, std::optional&lt; std::string &gt; user=std::nullopt, Flags... flags)'],['../structcppgres_1_1current__background__worker.html#a7576f073770d6e35b919b0602a67f946',1,'cppgres::current_background_worker::connect(oid db, std::optional&lt; oid &gt; user=std::nullopt, Flags... flags)']]],
  ['convertible_5ffrom_5fdatum_4',['convertible_from_datum',['../conceptcppgres_1_1convertible__from__datum.html',1,'cppgres']]],
  ['convertible_5ffrom_5fnullable_5fdatum_5',['convertible_from_nullable_datum',['../conceptcppgres_1_1convertible__from__nullable__datum.html',1,'cppgres']]],
  ['convertible_5finto_5fdatum_6',['convertible_into_datum',['../conceptcppgres_1_1convertible__into__datum.html',1,'cppgres']]],
  ['convertible_5finto_5fnullable_5fdatum_7',['convertible_into_nullable_datum',['../conceptcppgres_1_1convertible__into__nullable__datum.html',1,'cppgres']]],
  ['convertible_5finto_5fnullable_5fdatum_5fand_5fhas_5fa_5ftype_8',['convertible_into_nullable_datum_and_has_a_type',['../conceptcppgres_1_1convertible__into__nullable__datum__and__has__a__type.html',1,'cppgres']]],
  ['convertible_5finto_5fnullable_5fdatum_5for_5fset_5fiterator_5for_5fvoid_9',['convertible_into_nullable_datum_or_set_iterator_or_void',['../conceptcppgres_1_1convertible__into__nullable__datum__or__set__iterator__or__void.html',1,'cppgres']]],
  ['convertible_5fto_5fcstring_10',['convertible_to_cstring',['../conceptcppgres_1_1utils_1_1convertible__to__cstring.html',1,'cppgres::utils']]],
  ['cppgres_2ehpp_11',['cppgres.hpp',['../cppgres_8hpp.html',1,'']]],
  ['cppgres_3a_20postgres_20extensions_20in_20c_2b_2b_12',['Cppgres: Postgres extensions in C++',['../index.html',1,'']]],
  ['current_5fbackground_5fworker_13',['current_background_worker',['../structcppgres_1_1current__background__worker.html',1,'cppgres::current_background_worker'],['../structcppgres_1_1current__background__worker.html#a0d80d38d9f6c00c179ccace83c966d28',1,'cppgres::current_background_worker::current_background_worker()']]],
  ['current_5fpostgres_5ffunction_14',['current_postgres_function',['../structcppgres_1_1current__postgres__function.html',1,'cppgres']]],
  ['data_5flength_5favailable_15',['data_length_available',['../conceptcppgres_1_1utils_1_1data__length__available.html',1,'cppgres::utils']]],
  ['datumable_5ffunction_16',['datumable_function',['../conceptcppgres_1_1datumable__function.html',1,'cppgres']]],
  ['datumable_5fiterator_17',['datumable_iterator',['../conceptcppgres_1_1datumable__iterator.html',1,'cppgres']]],
  ['error_5fformattable_18',['error_formattable',['../conceptcppgres_1_1error__formattable.html',1,'cppgres']]],
  ['expanded_5fvarlena_5ftype_19',['expanded_varlena_type',['../conceptcppgres_1_1expanded__varlena__type.html',1,'cppgres']]],
  ['flattenable_20',['flattenable',['../conceptcppgres_1_1flattenable.html',1,'cppgres']]],
  ['has_5fa_5ftype_21',['has_a_type',['../conceptcppgres_1_1has__a__type.html',1,'cppgres']]],
  ['is_5fcstring_22',['is_cstring',['../conceptcppgres_1_1utils_1_1is__cstring.html',1,'cppgres::utils']]],
  ['is_5foptional_23',['is_optional',['../conceptcppgres_1_1utils_1_1is__optional.html',1,'cppgres::utils']]],
  ['node_24',['node',['../conceptcppgres_1_1node.html',1,'cppgres']]],
  ['node_5finherited_25',['node_inherited',['../conceptcppgres_1_1node__inherited.html',1,'cppgres']]],
  ['node_5finherited_5fbase_26',['node_inherited_base',['../conceptcppgres_1_1node__inherited__base.html',1,'cppgres']]],
  ['node_5ftagged_27',['node_tagged',['../conceptcppgres_1_1node__tagged.html',1,'cppgres']]],
  ['node_5fxpr_5ftagged_28',['node_xpr_tagged',['../conceptcppgres_1_1node__xpr__tagged.html',1,'cppgres']]],
  ['std_5ftuple_29',['std_tuple',['../conceptcppgres_1_1utils_1_1std__tuple.html',1,'cppgres::utils']]],
  ['syscached_30',['syscached',['../conceptcppgres_1_1syscached.html',1,'cppgres']]]
];
