node_mapping(List);
node_mapping(Alias);
node_mapping(RangeVar);
node_mapping(TableFunc);
node_mapping(IntoClause);
node_mapping(Var);
node_mapping(Const);
node_mapping(Param);
node_mapping(Aggref);
node_mapping(GroupingFunc);
node_mapping(WindowFunc);
#if PG_MAJORVERSION_NUM >= 17
node_mapping(WindowFuncRunCondition);
node_mapping(MergeSupportFunc);
#endif
node_mapping(SubscriptingRef);
node_mapping(FuncExpr);
node_mapping(NamedArgExpr);
node_mapping(OpExpr);
node_mapping_no_node_traits(DistinctExpr);
node_mapping_no_node_traits(NullIfExpr);
node_mapping(ScalarArrayOpExpr);
node_mapping(BoolExpr);
node_mapping(SubLink);
node_mapping(SubPlan);
node_mapping(AlternativeSubPlan);
node_mapping(FieldSelect);
node_mapping(FieldStore);
node_mapping(RelabelType);
node_mapping(CoerceViaIO);
node_mapping(ArrayCoerceExpr);
node_mapping(ConvertRowtypeExpr);
node_mapping(CollateExpr);
node_mapping(CaseExpr);
node_mapping(CaseWhen);
node_mapping(CaseTestExpr);
node_mapping(ArrayExpr);
node_mapping(RowExpr);
node_mapping(RowCompareExpr);
node_mapping(CoalesceExpr);
node_mapping(MinMaxExpr);
node_mapping(SQLValueFunction);
node_mapping(XmlExpr);
#if PG_MAJORVERSION_NUM >= 16
node_mapping(JsonFormat);
node_mapping(JsonReturning);
node_mapping(JsonValueExpr);
node_mapping(JsonConstructorExpr);
node_mapping(JsonIsPredicate);
#endif
#if PG_MAJORVERSION_NUM >= 17
node_mapping(JsonBehavior);
node_mapping(JsonExpr);
node_mapping(JsonTablePath);
node_mapping(JsonTablePathScan);
node_mapping(JsonTableSiblingJoin);
#endif
node_mapping(NullTest);
node_mapping(BooleanTest);
#if PG_MAJORVERSION_NUM >= 15
node_mapping(MergeAction);
#endif
node_mapping(CoerceToDomain);
node_mapping(CoerceToDomainValue);
node_mapping(SetToDefault);
node_mapping(CurrentOfExpr);
node_mapping(NextValueExpr);
node_mapping(InferenceElem);
#if PG_MAJORVERSION_NUM >= 18
node_mapping(ReturningExpr);
#endif
node_mapping(TargetEntry);
node_mapping(RangeTblRef);
node_mapping(JoinExpr);
node_mapping(FromExpr);
node_mapping(OnConflictExpr);
node_mapping(Query);
node_mapping(TypeName);
node_mapping(ColumnRef);
node_mapping(ParamRef);
node_mapping(A_Expr);
node_mapping(A_Const);
node_mapping(TypeCast);
node_mapping(CollateClause);
node_mapping(RoleSpec);
node_mapping(FuncCall);
node_mapping(A_Star);
node_mapping(A_Indices);
node_mapping(A_Indirection);
node_mapping(A_ArrayExpr);
node_mapping(ResTarget);
node_mapping(MultiAssignRef);
node_mapping(SortBy);
node_mapping(WindowDef);
node_mapping(RangeSubselect);
node_mapping(RangeFunction);
node_mapping(RangeTableFunc);
node_mapping(RangeTableFuncCol);
node_mapping(RangeTableSample);
node_mapping(ColumnDef);
node_mapping(TableLikeClause);
node_mapping(IndexElem);
node_mapping(DefElem);
node_mapping(LockingClause);
node_mapping(XmlSerialize);
node_mapping(PartitionElem);
#if PG_MAJORVERSION_NUM == 17
node_mapping(SinglePartitionSpec);
#endif
node_mapping(PartitionSpec);
node_mapping(PartitionBoundSpec);
node_mapping(PartitionRangeDatum);
node_mapping(PartitionCmd);
node_mapping(RangeTblEntry);
#if PG_MAJORVERSION_NUM >= 16
node_mapping(RTEPermissionInfo);
#endif
node_mapping(RangeTblFunction);
node_mapping(TableSampleClause);
node_mapping(WithCheckOption);
node_mapping(SortGroupClause);
node_mapping(GroupingSet);
node_mapping(WindowClause);
node_mapping(RowMarkClause);
node_mapping(WithClause);
node_mapping(InferClause);
node_mapping(OnConflictClause);
#if PG_MAJORVERSION_NUM >= 14
node_mapping(CTESearchClause);
node_mapping(CTECycleClause);
#endif
node_mapping(CommonTableExpr);
#if PG_MAJORVERSION_NUM >= 15
node_mapping(MergeWhenClause);
#endif
#if PG_MAJORVERSION_NUM >= 18
node_mapping(ReturningOption);
node_mapping(ReturningClause);
#endif
node_mapping(TriggerTransition);
#if PG_MAJORVERSION_NUM >= 16
node_mapping(JsonOutput);
#endif
#if PG_MAJORVERSION_NUM >= 17
node_mapping(JsonArgument);
node_mapping(JsonFuncExpr);
node_mapping(JsonTablePathSpec);
node_mapping(JsonTable);
node_mapping(JsonTableColumn);
node_mapping(JsonKeyValue);
node_mapping(JsonParseExpr);
node_mapping(JsonScalarExpr);
node_mapping(JsonSerializeExpr);
#endif
#if PG_MAJORVERSION_NUM >= 16
node_mapping(JsonObjectConstructor);
node_mapping(JsonArrayConstructor);
node_mapping(JsonArrayQueryConstructor);
node_mapping(JsonAggConstructor);
node_mapping(JsonObjectAgg);
node_mapping(JsonArrayAgg);
#endif
node_mapping(RawStmt);
node_mapping(InsertStmt);
node_mapping(DeleteStmt);
node_mapping(UpdateStmt);
#if PG_MAJORVERSION_NUM >= 15
node_mapping(MergeStmt);
#endif
node_mapping(SelectStmt);
node_mapping(SetOperationStmt);
#if PG_MAJORVERSION_NUM >= 14
node_mapping(ReturnStmt);
#endif
#if PG_MAJORVERSION_NUM >= 14
node_mapping(PLAssignStmt);
#endif
node_mapping(CreateSchemaStmt);
node_mapping(AlterTableStmt);
node_mapping(AlterTableCmd);
#if PG_MAJORVERSION_NUM >= 18
node_mapping(ATAlterConstraint);
#endif
node_mapping(ReplicaIdentityStmt);
node_mapping(AlterCollationStmt);
node_mapping(AlterDomainStmt);
node_mapping(GrantStmt);
node_mapping(ObjectWithArgs);
node_mapping(AccessPriv);
node_mapping(GrantRoleStmt);
node_mapping(AlterDefaultPrivilegesStmt);
node_mapping(CopyStmt);
node_mapping(VariableSetStmt);
node_mapping(VariableShowStmt);
node_mapping(CreateStmt);
node_mapping(Constraint);
node_mapping(CreateTableSpaceStmt);
node_mapping(DropTableSpaceStmt);
node_mapping(AlterTableSpaceOptionsStmt);
node_mapping(AlterTableMoveAllStmt);
node_mapping(CreateExtensionStmt);
node_mapping(AlterExtensionStmt);
node_mapping(AlterExtensionContentsStmt);
node_mapping(CreateFdwStmt);
node_mapping(AlterFdwStmt);
node_mapping(CreateForeignServerStmt);
node_mapping(AlterForeignServerStmt);
node_mapping(CreateForeignTableStmt);
node_mapping(CreateUserMappingStmt);
node_mapping(AlterUserMappingStmt);
node_mapping(DropUserMappingStmt);
node_mapping(ImportForeignSchemaStmt);
node_mapping(CreatePolicyStmt);
node_mapping(AlterPolicyStmt);
node_mapping(CreateAmStmt);
node_mapping(CreateTrigStmt);
node_mapping(CreateEventTrigStmt);
node_mapping(AlterEventTrigStmt);
node_mapping(CreatePLangStmt);
node_mapping(CreateRoleStmt);
node_mapping(AlterRoleStmt);
node_mapping(AlterRoleSetStmt);
node_mapping(DropRoleStmt);
node_mapping(CreateSeqStmt);
node_mapping(AlterSeqStmt);
node_mapping(DefineStmt);
node_mapping(CreateDomainStmt);
node_mapping(CreateOpClassStmt);
node_mapping(CreateOpClassItem);
node_mapping(CreateOpFamilyStmt);
node_mapping(AlterOpFamilyStmt);
node_mapping(DropStmt);
node_mapping(TruncateStmt);
node_mapping(CommentStmt);
node_mapping(SecLabelStmt);
node_mapping(DeclareCursorStmt);
node_mapping(ClosePortalStmt);
node_mapping(FetchStmt);
node_mapping(IndexStmt);
node_mapping(CreateStatsStmt);
#if PG_MAJORVERSION_NUM >= 14
node_mapping(StatsElem);
#endif
node_mapping(AlterStatsStmt);
node_mapping(CreateFunctionStmt);
node_mapping(FunctionParameter);
node_mapping(AlterFunctionStmt);
node_mapping(DoStmt);
node_mapping(InlineCodeBlock);
node_mapping(CallStmt);
node_mapping(CallContext);
node_mapping(RenameStmt);
node_mapping(AlterObjectDependsStmt);
node_mapping(AlterObjectSchemaStmt);
node_mapping(AlterOwnerStmt);
node_mapping(AlterOperatorStmt);
node_mapping(AlterTypeStmt);
node_mapping(RuleStmt);
node_mapping(NotifyStmt);
node_mapping(ListenStmt);
node_mapping(UnlistenStmt);
node_mapping(TransactionStmt);
node_mapping(CompositeTypeStmt);
node_mapping(CreateEnumStmt);
node_mapping(CreateRangeStmt);
node_mapping(AlterEnumStmt);
node_mapping(ViewStmt);
node_mapping(LoadStmt);
node_mapping(CreatedbStmt);
node_mapping(AlterDatabaseStmt);
#if PG_MAJORVERSION_NUM >= 15
node_mapping(AlterDatabaseRefreshCollStmt);
#endif
node_mapping(AlterDatabaseSetStmt);
node_mapping(DropdbStmt);
node_mapping(AlterSystemStmt);
node_mapping(ClusterStmt);
node_mapping(VacuumStmt);
node_mapping(VacuumRelation);
node_mapping(ExplainStmt);
node_mapping(CreateTableAsStmt);
node_mapping(RefreshMatViewStmt);
node_mapping(CheckPointStmt);
node_mapping(DiscardStmt);
node_mapping(LockStmt);
node_mapping(ConstraintsSetStmt);
node_mapping(ReindexStmt);
node_mapping(CreateConversionStmt);
node_mapping(CreateCastStmt);
node_mapping(CreateTransformStmt);
node_mapping(PrepareStmt);
node_mapping(ExecuteStmt);
node_mapping(DeallocateStmt);
node_mapping(DropOwnedStmt);
node_mapping(ReassignOwnedStmt);
node_mapping(AlterTSDictionaryStmt);
node_mapping(AlterTSConfigurationStmt);
#if PG_MAJORVERSION_NUM >= 15
node_mapping(PublicationTable);
node_mapping(PublicationObjSpec);
#endif
node_mapping(CreatePublicationStmt);
node_mapping(AlterPublicationStmt);
node_mapping(CreateSubscriptionStmt);
node_mapping(AlterSubscriptionStmt);
node_mapping(DropSubscriptionStmt);
node_mapping(PlannerGlobal);
node_mapping(PlannerInfo);
node_mapping(RelOptInfo);
node_mapping(IndexOptInfo);
node_mapping(ForeignKeyOptInfo);
node_mapping(StatisticExtInfo);
#if PG_MAJORVERSION_NUM >= 16
node_mapping(JoinDomain);
#endif
node_mapping(EquivalenceClass);
node_mapping(EquivalenceMember);
node_mapping(PathKey);
#if PG_MAJORVERSION_NUM >= 17
node_mapping(GroupByOrdering);
#endif
node_mapping(PathTarget);
node_mapping(ParamPathInfo);
node_mapping(Path);
node_mapping(IndexPath);
node_mapping(IndexClause);
node_mapping(BitmapHeapPath);
node_mapping(BitmapAndPath);
node_mapping(BitmapOrPath);
node_mapping(TidPath);
#if PG_MAJORVERSION_NUM >= 14
node_mapping(TidRangePath);
#endif
node_mapping(SubqueryScanPath);
node_mapping(ForeignPath);
node_mapping(CustomPath);
node_mapping(AppendPath);
node_mapping(MergeAppendPath);
node_mapping(GroupResultPath);
node_mapping(MaterialPath);
#if PG_MAJORVERSION_NUM >= 14
node_mapping(MemoizePath);
#endif
node_mapping(UniquePath);
node_mapping(GatherPath);
node_mapping(GatherMergePath);
node_mapping(NestPath);
node_mapping(MergePath);
node_mapping(HashPath);
node_mapping(ProjectionPath);
node_mapping(ProjectSetPath);
node_mapping(SortPath);
node_mapping(IncrementalSortPath);
node_mapping(GroupPath);
#if PG_MAJORVERSION_NUM < 19
node_mapping(UpperUniquePath);
#endif
node_mapping(AggPath);
node_mapping(GroupingSetData);
node_mapping(RollupData);
node_mapping(GroupingSetsPath);
node_mapping(MinMaxAggPath);
node_mapping(WindowAggPath);
node_mapping(SetOpPath);
node_mapping(RecursiveUnionPath);
node_mapping(LockRowsPath);
node_mapping(ModifyTablePath);
node_mapping(LimitPath);
node_mapping(RestrictInfo);
node_mapping(PlaceHolderVar);
node_mapping(SpecialJoinInfo);
#if PG_MAJORVERSION_NUM >= 16
node_mapping(OuterJoinClauseInfo);
#endif
node_mapping(AppendRelInfo);
#if PG_MAJORVERSION_NUM >= 14
node_mapping(RowIdentityVarInfo);
#endif
node_mapping(PlaceHolderInfo);
node_mapping(MinMaxAggInfo);
node_mapping(PlannerParamItem);
#if PG_MAJORVERSION_NUM >= 16
node_mapping(AggInfo);
node_mapping(AggTransInfo);
#endif
#if PG_MAJORVERSION_NUM >= 18
node_mapping(UniqueRelInfo);
#endif
node_mapping(PlannedStmt);
node_mapping(Result);
node_mapping(ProjectSet);
node_mapping(ModifyTable);
node_mapping(Append);
node_mapping(MergeAppend);
node_mapping(RecursiveUnion);
node_mapping(BitmapAnd);
node_mapping(BitmapOr);
node_mapping(SeqScan);
node_mapping(SampleScan);
node_mapping(IndexScan);
node_mapping(IndexOnlyScan);
node_mapping(BitmapIndexScan);
node_mapping(BitmapHeapScan);
node_mapping(TidScan);
#if PG_MAJORVERSION_NUM >= 14
node_mapping(TidRangeScan);
#endif
node_mapping(SubqueryScan);
node_mapping(FunctionScan);
node_mapping(ValuesScan);
node_mapping(TableFuncScan);
node_mapping(CteScan);
node_mapping(NamedTuplestoreScan);
node_mapping(WorkTableScan);
node_mapping(ForeignScan);
node_mapping(CustomScan);
node_mapping(NestLoop);
node_mapping(NestLoopParam);
node_mapping(MergeJoin);
node_mapping(HashJoin);
node_mapping(Material);
#if PG_MAJORVERSION_NUM >= 14
node_mapping(Memoize);
#endif
node_mapping(Sort);
node_mapping(IncrementalSort);
node_mapping(Group);
node_mapping(Agg);
node_mapping(WindowAgg);
node_mapping(Unique);
node_mapping(Gather);
node_mapping(GatherMerge);
node_mapping(Hash);
node_mapping(SetOp);
node_mapping(LockRows);
node_mapping(Limit);
node_mapping(PlanRowMark);
node_mapping(PartitionPruneInfo);
node_mapping(PartitionedRelPruneInfo);
node_mapping(PartitionPruneStepOp);
node_mapping(PartitionPruneStepCombine);
node_mapping(PlanInvalItem);
node_mapping(ExprState);
node_mapping(IndexInfo);
node_mapping(ExprContext);
node_mapping(ReturnSetInfo);
node_mapping(ProjectionInfo);
node_mapping(JunkFilter);
node_mapping(OnConflictSetState);
#if PG_MAJORVERSION_NUM >= 15
node_mapping(MergeActionState);
#endif
node_mapping(ResultRelInfo);
node_mapping(EState);
node_mapping(WindowFuncExprState);
node_mapping(SetExprState);
node_mapping(SubPlanState);
node_mapping(DomainConstraintState);
node_mapping(ResultState);
node_mapping(ProjectSetState);
node_mapping(ModifyTableState);
node_mapping(AppendState);
node_mapping(MergeAppendState);
node_mapping(RecursiveUnionState);
node_mapping(BitmapAndState);
node_mapping(BitmapOrState);
node_mapping(ScanState);
node_mapping(SeqScanState);
node_mapping(SampleScanState);
node_mapping(IndexScanState);
node_mapping(IndexOnlyScanState);
node_mapping(BitmapIndexScanState);
node_mapping(BitmapHeapScanState);
node_mapping(TidScanState);
#if PG_MAJORVERSION_NUM >= 14
node_mapping(TidRangeScanState);
#endif
node_mapping(SubqueryScanState);
node_mapping(FunctionScanState);
node_mapping(ValuesScanState);
node_mapping(TableFuncScanState);
node_mapping(CteScanState);
node_mapping(NamedTuplestoreScanState);
node_mapping(WorkTableScanState);
node_mapping(ForeignScanState);
node_mapping(CustomScanState);
node_mapping(JoinState);
node_mapping(NestLoopState);
node_mapping(MergeJoinState);
node_mapping(HashJoinState);
node_mapping(MaterialState);
#if PG_MAJORVERSION_NUM >= 14
node_mapping(MemoizeState);
#endif
node_mapping(SortState);
node_mapping(IncrementalSortState);
node_mapping(GroupState);
node_mapping(AggState);
node_mapping(WindowAggState);
node_mapping(UniqueState);
node_mapping(GatherState);
node_mapping(GatherMergeState);
node_mapping(HashState);
node_mapping(SetOpState);
node_mapping(LockRowsState);
node_mapping(LimitState);
node_mapping(IndexAmRoutine);
node_mapping(TableAmRoutine);
node_mapping(TsmRoutine);
node_mapping(EventTriggerData);
node_mapping(TriggerData);
node_mapping(TupleTableSlot);
node_mapping(FdwRoutine);
#if PG_MAJORVERSION_NUM >= 16
node_mapping(Bitmapset);
#endif
node_mapping(ExtensibleNode);
#if PG_MAJORVERSION_NUM >= 16
node_mapping(ErrorSaveContext);
#endif
node_mapping(IdentifySystemCmd);
node_mapping(BaseBackupCmd);
node_mapping(CreateReplicationSlotCmd);
node_mapping(DropReplicationSlotCmd);
#if PG_MAJORVERSION_NUM >= 17
node_mapping(AlterReplicationSlotCmd);
#endif
node_mapping(StartReplicationCmd);
#if PG_MAJORVERSION_NUM >= 15
node_mapping(ReadReplicationSlotCmd);
#endif
node_mapping(TimeLineHistoryCmd);
#if PG_MAJORVERSION_NUM >= 17
node_mapping(UploadManifestCmd);
#endif
node_mapping(SupportRequestSimplify);
node_mapping(SupportRequestSelectivity);
node_mapping(SupportRequestCost);
node_mapping(SupportRequestRows);
node_mapping(SupportRequestIndexCondition);
#if PG_MAJORVERSION_NUM >= 15
node_mapping(SupportRequestWFuncMonotonic);
#endif
#if PG_MAJORVERSION_NUM >= 17
node_mapping(SupportRequestOptimizeWindowClause);
#endif
#if PG_MAJORVERSION_NUM >= 18
node_mapping(SupportRequestModifyInPlace);
#endif
#if PG_MAJORVERSION_NUM >= 15
node_mapping(Integer);
node_mapping(Float);
node_mapping(Boolean);
node_mapping(String);
node_mapping(BitString);
#endif
node_mapping(ForeignKeyCacheInfo);
